package my_pokedex.model.move;

import java.util.HashMap;

import my_pokedex.model.TYPE;

public class Weakness_Table {

	public static HashMap<TYPE, HashMap<TYPE,EFFECTIVENESS>> table = new HashMap<TYPE, HashMap<TYPE,EFFECTIVENESS>>() {{
		put(TYPE.NORMAL, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.FIRE, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.RESISTANT);
			put(TYPE.WATER,EFFECTIVENESS.WEAK);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.RESISTANT);
			put(TYPE.ICE,EFFECTIVENESS.RESISTANT);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.WEAK);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.RESISTANT);
			put(TYPE.ROCK,EFFECTIVENESS.WEAK);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.RESISTANT);
			put(TYPE.FAIRY,EFFECTIVENESS.RESISTANT);
		}});
		
		put(TYPE.WATER, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.RESISTANT);
			put(TYPE.WATER,EFFECTIVENESS.RESISTANT);
			put(TYPE.ELECTRIC,EFFECTIVENESS.WEAK);
			put(TYPE.GRASS,EFFECTIVENESS.WEAK);
			put(TYPE.ICE,EFFECTIVENESS.RESISTANT);
			put(TYPE.FIGHTING,EFFECTIVENESS.NORMAL);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.NORMAL);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.RESISTANT);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.ELECTRIC, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.GRASS, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.ICE, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.FIGHTING, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.POISON, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.GROUND, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.FLYING, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.PSYCHIC, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.BUG, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.ROCK, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.GHOST, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.DRAGON, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.DARK, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.STEEL, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
		
		put(TYPE.FAIRY, new HashMap<TYPE,EFFECTIVENESS>() {{
			put(TYPE.NORMAL,EFFECTIVENESS.NORMAL);
			put(TYPE.FIRE,EFFECTIVENESS.NORMAL);
			put(TYPE.WATER,EFFECTIVENESS.NORMAL);
			put(TYPE.ELECTRIC,EFFECTIVENESS.NORMAL);
			put(TYPE.GRASS,EFFECTIVENESS.NORMAL);
			put(TYPE.ICE,EFFECTIVENESS.NORMAL);
			put(TYPE.FIGHTING,EFFECTIVENESS.WEAK);
			put(TYPE.POISON,EFFECTIVENESS.NORMAL);
			put(TYPE.GROUND,EFFECTIVENESS.NORMAL);
			put(TYPE.FLYING,EFFECTIVENESS.NORMAL);
			put(TYPE.PSYCHIC,EFFECTIVENESS.NORMAL);
			put(TYPE.BUG,EFFECTIVENESS.NORMAL);
			put(TYPE.ROCK,EFFECTIVENESS.NORMAL);
			put(TYPE.GHOST,EFFECTIVENESS.IMMUNE);
			put(TYPE.DRAGON,EFFECTIVENESS.NORMAL);
			put(TYPE.DARK,EFFECTIVENESS.NORMAL);
			put(TYPE.STEEL,EFFECTIVENESS.NORMAL);
			put(TYPE.FAIRY,EFFECTIVENESS.NORMAL);
		}});
	}};
}
